version: '2'


services:
    mongodb:
        build: 
            ./mongodb
        image: 
            duchaxello/mongo:1.0
        container_name:
            mongodb_2
        ports:
            - "27017:27017"
        networks:
            net_local:
                ipv4_address: 10.45.0.2


networks:
    net_local:
        ipam:
            driver: default
            config:
                - subnet: 10.45.0.1/24
                  gateway: 10.45.0.99










